#开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false   #开发阶段关闭缓存
  datasource:
    url: jdbc:mysql://localhost:3306/vmcontrol
    username: root
    password: Mydear129520
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
user:
  password:
    maxRetryCount: 5

## Shiro
#shiro:
#  user:
#    # 登录地址
#    loginUrl: /kvm/login
#    # 权限认证失败地址
#    unauthorizedUrl: /unauth
#    # 首页地址
#    indexUrl: /kvm/index
#    # 验证码开关
#    captchaEnabled: true
#    # 验证码类型 math 数组计算 char 字符
#    captchaType: math
#  cookie:
#    # 设置Cookie的域名 默认空，即当前访问的域名
#    domain:
#    # 设置cookie的有效访问路径
#    path: /
#    # 设置HttpOnly属性
#    httpOnly: true
#    # 设置Cookie的过期时间，天为单位
#    maxAge: 30
#  session:
#    # Session超时时间，-1代表永不过期（默认30分钟）
#    expireTime: 30
#    # 同步session到数据库的周期（默认1分钟）
#    dbSyncPeriod: 1
#    # 相隔多久检查一次session的有效性，默认就是10分钟
#    validationInterval: 10
#    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
#    maxSession: -1
#    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
#    kickoutAfter: false
